FROM golang:1.25.1-alpine

RUN go install github.com/air-verse/air@latest 
RUN go install github.com/swaggo/swag/cmd/swag@latest

WORKDIR /var/www

COPY go.mod go.sum ./
RUN --mount=type=cache,target=/go/pkg/mod/cache \
  go mod download

COPY .air.toml ./

COPY . .

RUN mkdir -p tmp

EXPOSE 8080

# Генерируем документацию перед запуском
RUN swag init -g cmd/app/main.go -o docs/

CMD ["air", "-c", ".air.toml"]
